// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCjIoRqEemGsWW2nVbj4kKlBTv7HqWqEC4',
//     appId: '1:810503938108:web:6e4ce0020b433c09cf6339',
//     messagingSenderId: '810503938108',
//     projectId: 'goal-tracking-55fad',
//     authDomain: 'goal-tracking-55fad.firebaseapp.com',
//     storageBucket: 'goal-tracking-55fad.appspot.com',
//     measurementId: 'G-RWEBBPQSVS',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBmQmn7ZMtGFgfJcDMLBRNo_kcXHSTgbkA',
//     appId: '1:810503938108:android:71a93720b2730cb7cf6339',
//     messagingSenderId: '810503938108',
//     projectId: 'goal-tracking-55fad',
//     storageBucket: 'goal-tracking-55fad.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC0Pz-PJ4aZ9r17f2lJZNDPFP3iAup3HbA',
//     appId: '1:810503938108:ios:cb6c81a1b7e40a0fcf6339',
//     messagingSenderId: '810503938108',
//     projectId: 'goal-tracking-55fad',
//     storageBucket: 'goal-tracking-55fad.appspot.com',
//     androidClientId: '810503938108-b8455fv62p0jbt5lep65ia3u5gkle696.apps.googleusercontent.com',
//     iosClientId: '810503938108-5kgmch0eubkk7m2jnjt806e27n0sk0ft.apps.googleusercontent.com',
//     iosBundleId: 'com.example.goalTracking',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC0Pz-PJ4aZ9r17f2lJZNDPFP3iAup3HbA',
//     appId: '1:810503938108:ios:cb6c81a1b7e40a0fcf6339',
//     messagingSenderId: '810503938108',
//     projectId: 'goal-tracking-55fad',
//     storageBucket: 'goal-tracking-55fad.appspot.com',
//     androidClientId: '810503938108-b8455fv62p0jbt5lep65ia3u5gkle696.apps.googleusercontent.com',
//     iosClientId: '810503938108-5kgmch0eubkk7m2jnjt806e27n0sk0ft.apps.googleusercontent.com',
//     iosBundleId: 'com.example.goalTracking',
//   );
// }
